---
title: "FAIR_Knitter"
author: "Zachary Gold"
date: "2026-09-17"
output: html_document
---

```{r}
library(tidyverse)
library(rmarkdown)
library(here)
library(readxl)
```

# Read in Saple Metadata
```{r}

sample_metadata<- read_excel(here("raw_data","qPCR_raw_data","ElectronicArchive_CruiseSampleMetadata_20250516_FHL.xlsx"), sheet="Electronic Archive") %>% filter(., !is.na(Sample_Name))
```

# Read in FAIRe BeBOP
```{r}

# Read all lines and find the YAML boundaries
raw_lines_SR_collect_bebop <- read_lines("FAIRe/PMEL/NOAA-PMEL-OME_eDNA_Collection_Protocol_SmithRoot_PeristalticPump.md")
bounds_SR_collect_bebop <- which(raw_lines_SR_collect_bebop == "---")

# Extract the header lines into a tibble
PMEL_SR_collect_bebop_list <- tibble(raw_text = raw_lines_SR_collect_bebop[(bounds_SR_collect_bebop[1] + 1):(bounds_SR_collect_bebop[2] - 1)]) |> 
  # Remove empty lines
  filter(trimws(raw_text) != "") |> 
  # Create a category column by detecting the '#' symbol and removing it
  mutate(
    category = if_else(str_starts(raw_text, "#"), str_remove(raw_text, "^#\\s*"), NA_character_)
  ) |> 
  # Fill the category names down to the subsequent rows
  fill(category, .direction = "down") |> 
  # Drop the original comment rows now that the category is assigned
  filter(!str_starts(raw_text, "#")) |> 
  # Split the text into term and value at the first colon
  # extra = "merge" ensures we don't accidentally split values that contain colons
  separate(raw_text, into = c("term", "value"), sep = ":\\s*", extra = "merge") |> 
  # Clean up any rogue whitespace
  mutate(across(everything(), str_trim))

# Read all lines and find the YAML boundaries
raw_lines_Stx_collect_bebop <- read_lines("FAIRe/PMEL/NOAA-PMEL-OME_eDNA_Collection_Protocol_Sterivex_PeristalticPump.md")
bounds_Stx_collect_bebop <- which(raw_lines_Stx_collect_bebop == "---")

# Extract the header lines into a tibble

PMEL_Stx_collect_bebop_list <- tibble(raw_text = raw_lines_Stx_collect_bebop[(bounds_Stx_collect_bebop[1] + 1):(bounds_Stx_collect_bebop[2] - 1)]) |> 
  # Remove empty lines
  filter(trimws(raw_text) != "") |> 
  # Create a category column by detecting the '#' symbol and removing it
  mutate(
    category = if_else(str_starts(raw_text, "#"), str_remove(raw_text, "^#\\s*"), NA_character_)
  ) |> 
  # Fill the category names down to the subsequent rows
  fill(category, .direction = "down") |> 
  # Drop the original comment rows now that the category is assigned
  filter(!str_starts(raw_text, "#")) |> 
  # Split the text into term and value at the first colon
  # extra = "merge" ensures we don't accidentally split values that contain colons
  separate(raw_text, into = c("term", "value"), sep = ":\\s*", extra = "merge") |> 
  # Clean up any rogue whitespace
  mutate(across(everything(), str_trim))




# Read all lines and find the YAML boundaries
raw_lines_Stx_extr_bebop <- read_lines("FAIRe/PMEL/NOAA-PMEL-OME_eDNA_Sterivex_Extraction_Protocol_Centrifuge.md")
bounds_Stx_extr_bebop <- which(raw_lines_Stx_extr_bebop == "---")

# Extract the header lines into a tibble
PMEL_Stx_extr_bebop_list <- tibble(raw_text = raw_lines_Stx_extr_bebop[(bounds_Stx_collect_bebop[1] + 1):(bounds_Stx_collect_bebop[2] - 1)]) |> 
  # Remove empty lines
  filter(trimws(raw_text) != "") |> 
  # Create a category column by detecting the '#' symbol and removing it
  mutate(
    category = if_else(str_starts(raw_text, "#"), str_remove(raw_text, "^#\\s*"), NA_character_)
  ) |> 
  # Fill the category names down to the subsequent rows
  fill(category, .direction = "down") |> 
  # Drop the original comment rows now that the category is assigned
  filter(!str_starts(raw_text, "#")) |> 
  # Split the text into term and value at the first colon
  # extra = "merge" ensures we don't accidentally split values that contain colons
  separate(raw_text, into = c("term", "value"), sep = ":\\s*", extra = "merge") |> 
  # Clean up any rogue whitespace
  mutate(across(everything(), str_trim))




# Read all lines and find the YAML boundaries
raw_lines_SR_extr_bebop <- read_lines("FAIRe/PMEL/NOAA-PMEL-OME_eDNA_DiscFilters_Extraction_Protocol_Centrifuge.md")
bounds_SR_extr_bebop <- which(raw_lines_SR_extr_bebop == "---")

# Extract the header lines into a tibble

PMEL_SR_extr_bebop_list <- tibble(raw_text = raw_lines_SR_extr_bebop[(bounds_SR_extr_bebop[1] + 1):(bounds_SR_extr_bebop[2] - 1)]) |> 
  # Remove empty lines
  filter(trimws(raw_text) != "") |> 
  # Create a category column by detecting the '#' symbol and removing it
  mutate(
    category = if_else(str_starts(raw_text, "#"), str_remove(raw_text, "^#\\s*"), NA_character_)
  ) |> 
  # Fill the category names down to the subsequent rows
  fill(category, .direction = "down") |> 
  # Drop the original comment rows now that the category is assigned
  filter(!str_starts(raw_text, "#")) |> 
  # Split the text into term and value at the first colon
  # extra = "merge" ensures we don't accidentally split values that contain colons
  separate(raw_text, into = c("term", "value"), sep = ":\\s*", extra = "merge") |> 
  # Clean up any rogue whitespace
  mutate(across(everything(), str_trim))

# Read all lines and find the YAML boundaries
raw_lines_qPCR_bebop <- read_lines("FAIRe/PMEL/NOAA-PMEL-OME_Pycno_nad5_v1_qPCR_Protocol_BeBOP.md")
bounds_qPCR_bebop <- which(raw_lines_qPCR_bebop == "---")

# Extract the header lines into a tibble

PMEL_qPCR_bebop_list <- tibble(raw_text = raw_lines_qPCR_bebop[(bounds_qPCR_bebop[1] + 1):(bounds_qPCR_bebop[2] - 1)]) |> 
  # Remove empty lines
  filter(trimws(raw_text) != "") |> 
  # Create a category column by detecting the '#' symbol and removing it
  mutate(
    category = if_else(str_starts(raw_text, "#"), str_remove(raw_text, "^#\\s*"), NA_character_)
  ) |> 
  # Fill the category names down to the subsequent rows
  fill(category, .direction = "down") |> 
  # Drop the original comment rows now that the category is assigned
  filter(!str_starts(raw_text, "#")) |> 
  # Split the text into term and value at the first colon
  # extra = "merge" ensures we don't accidentally split values that contain colons
  separate(raw_text, into = c("term", "value"), sep = ":\\s*", extra = "merge") |> 
  # Clean up any rogue whitespace
  mutate(across(everything(), str_trim))

```

```{r}
bind_rows(PMEL_SR_collect_bebop_list,PMEL_Stx_collect_bebop_list,PMEL_Stx_extr_bebop_list,PMEL_SR_extr_bebop_list,PMEL_qPCR_bebop_list) -> bebop_total

bebop_total %>% 
  filter(., category =="MIOP terms") %>% 
  distinct() -> miop_terms

miop_terms %>% 
  group_by(term) %>% 
  summarise(value = paste(value, collapse = ";"), .groups = "drop") %>% 
  mutate(., value = if_else(term=="creator","Han Weinrich, Zachary Gold, Shannon Brown, Sean McAllister",value)) %>% mutate(., `term:value`=str_c(term,":",value)) %>% ungroup() %>% dplyr::select(`term:value`) -> miop_unique

as.list(miop_unique) -> miop_unique_list

miop_unique_values <- paste(miop_unique_list$`term:value`, collapse = "|")
```

# Read in FAIRe Checklist information
```{r}
FAIRe_projectMetadata_checklist <- read_xlsx(here("FAIRe/FAIRe_checklist_v1.0.2_FULLtemplate.xlsx"), sheet="projectMetadata")

FAIRe_sampleMetadata_checklist <- read_xlsx(here("FAIRe/FAIRe_checklist_v1.0.2_FULLtemplate.xlsx"), sheet="sampleMetadata") 

FAIRe_sampleMetadata_checklist <- unlist(FAIRe_sampleMetadata_checklist[2, ], use.names = FALSE) %>% as_tibble_col(column_name = "term") 

FAIRe_stdData_checklist <- read_xlsx(here("FAIRe/FAIRe_checklist_v1.0.2_FULLtemplate.xlsx"), sheet="stdData") 

FAIRe_stdData_checklist <- unlist(FAIRe_stdData_checklist[2, ], use.names = FALSE) %>% as_tibble_col(column_name = "term") 

FAIRe_ampData_checklist <- read_xlsx(here("FAIRe/FAIRe_checklist_v1.0.2_FULLtemplate.xlsx"), sheet="ampData") 

FAIRe_ampData_checklist <- unlist(FAIRe_ampData_checklist[2, ], use.names = FALSE) %>% as_tibble_col(column_name = "term")

FAIRe_eLowQuantData_checklist <- read_xlsx(here("FAIRe/FAIRe_checklist_v1.0.2_FULLtemplate.xlsx"), sheet="eLowQuantData") 

FAIRe_eLowQuantData_checklist <- unlist(FAIRe_eLowQuantData_checklist[2, ], use.names = FALSE) %>% as_tibble_col(column_name = "term") 


```

# Project Metadata

## Mapping of Values
```{r}

sample_metadata %>% 
   mutate(., Bottle_Name = str_extract(Sample_Name, "^[^.]+")) %>% 
  group_by(Bottle_Name) %>% 
  mutate(., biological_rep= max(Biological_Replicate)) %>% 
   rename(recordedBy =Personnel_responsible_for_Collecting_Sample) %>% 
  mutate(., recordedByID= "https://orcid.org/0000-0003-0490-7630",
         project_contact = "zachary.gold@noaa.gov",
         institution= "NOAA Pacific Marine Environmental Laboratory",
         institutionID= "03crn0n59",
         project_name = "Molecular Star Gazing: Development and Validation of an Environmental DNA Assay for the Imperiled Sunflower Sea Star (Pycnopodia helianthoides)",
         project_id = "Pycnopodia_eDNA_assay_validation_MS",
         parent_project_id = "NOAA_PMEL_OME",
         study_factor = miop_unique_values,
         assay_type = "targeted",
         sterilise_method = "https://doi.org/10.5281/zenodo.16945434",
         neg_cont_0_1 = 1,
         pos_cont_0_1 = 1,
         checkls_ver = "1.0.2",
         mod_date = "2026-09-17",
         license = "CC0 1.0 Universal",
         rightsHolder ="NOAA PMEL",
         accessRights="Universal",
         informationWithheld=NA,
         dataGeneralizations=NA,
         bibliographicCitation="https://doi.org/10.5281/zenodo.20076925",
         associated_resource="https://doi.org/10.64898/2026.05.07.723600",
         code_repo="https://github.com/marinednadude/Pycnopodia_eDNA_assay_validation_MS",
         biological_rep = biological_rep,
         pcr_0_1 = 1,
         inhibition_check_0_1=1,
         inhibition_check="https://doi.org/10.5281/zenodo.19711947",
         thermocycler = PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="thermocycler")],
         assay_name=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="assay_name")],
         assay_validation=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="assay_validation")],
         targetTaxonomicAssay=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="targetTaxonomicAssay")],
        targetTaxonomicScope="",
        target_gene=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="target_gene")],
        target_subfragment="",
        target_subfragment="",
        ampliconSize=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="ampliconSize")],
        pcr_primer_forward=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_forward")],
        pcr_primer_reverse=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_reverse")],
        pcr_primer_name_forward=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_name_forward")],
        pcr_primer_name_reverse=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_name_reverse")],
        pcr_primer_reference_forward="https://doi.org/10.64898/2026.05.07.723600",
        pcr_primer_reference_reverse="https://doi.org/10.64898/2026.05.07.723600",
        pcr_primer_vol_forward=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_vol_forward")],
        pcr_primer_vol_reverse=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_vol_reverse")],                                                                              
        pcr_primer_conc_forward=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_conc_forward")],
        pcr_primer_conc_reverse=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_primer_conc_reverse")],
        probeReporter=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="probeReporter")],
        probeQuencher=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="probeQuencher")],
        probeQuencher=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="probeQuencher")],
        probe_seq=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="probe_seq")],
        probe_ref="https://doi.org/10.64898/2026.05.07.723600",
        probe_conc=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="probe_conc")],
        commercial_mm=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="commercial_mm")],
        custom_mm=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="custom_mm")],
        block_seq=NA,
        block_ref=NA,
        block_taxa=NA,
        amplificationReactionVolume=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="amplificationReactionVolume")],
        pcr_dna_vol=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_dna_vol")],
        pcr_rep=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_rep")],
        nucl_acid_amp="https://doi.org/10.64898/2026.05.07.723600",
        pcr_cond=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_cond")],
        annealingTemp=60,
        pcr_cycles=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_cycles")],
        pcr_analysis_software=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_analysis_software")],
        pcr_method_additional=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_method_additional")],
        amp_vis_method=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="amp_vis_method")],
        detection_criteria=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="detection_criteria")],
        lod_method=paste0(PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="lod_method")],"|"," https://doi.org/10.1002/edn3.220"),
        pcr_assay_lod_techreps=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_lod_techreps")],
        pcr_assay_lod=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_lod")],
        pcr_assay_lod_unit="copies/reaction",
        pcr_assay_lod_UL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_lod_UL")],
        pcr_assay_lod_LL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_lod_LL")],
        loq_method=paste0(PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="loq_method")],"|"," https://doi.org/10.1002/edn3.220"),
        pcr_assay_loq_techreps=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_loq_techreps")],
        pcr_assay_loq=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_loq")],
        pcr_assay_loq_unit=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_loq_unit")],
        pcr_assay_loq_UL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_loq_UL")],
        pcr_assay_loq_LL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="pcr_assay_loq_LL")],
        elowquant_lod_method	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_lod_method")],
                                                         elowquant_pcr_assay_lod_techreps	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_lod_techreps")],
        elowquant_pcr_assay_lod	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_lod")],
        elowquant_pcr_assay_lod_unit	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_lod_unit")],
        elowquant_pcr_assay_lod_UL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_lod_UL")],
        elowquant_pcr_assay_lod_LL	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_lod_LL")],
        elowquant_loq_method	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_loq_method")],
        elowquant_pcr_assay_loq_techreps	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_loq_techreps")],
        elowquant_pcr_assay_loq	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_loq")],
        elowquant_pcr_assay_loq_unit	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_loq_unit")],
        elowquant_pcr_assay_loq_UL	=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_loq_UL")],
        elowquant_pcr_assay_loq_LL=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="elowquant_pcr_assay_loq_LL")],
        std_type=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="std_type")],
        std_source=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="std_source")],
        std_seq=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="std_seq")],
        thresholdQuantificationCycle=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="thresholdQuantificationCycle")],
        baselineValue=10,
        automaticThresholdQuantificationCycle=0,
        automaticBaselineValue=0,
        targeted_detection_method_additional="",
        estimatedNumberOfCopies_method=PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="estimatedNumberOfCopies_method")]) -> sample_projectMetadata_pycno

```


## Check for Completeness
```{r}
PMEL_qPCR_bebop_list %>% 
  filter(., category=="FAIRe terms") -> bebop_faire_qPCR_terms

setdiff(bebop_faire_qPCR_terms$term,colnames(sample_projectMetadata_pycno))

FAIRe_projectMetadata_checklist %>% 
  filter(., section %in% c("Project","Data management","Sample collection","PCR","Targeted assay detection")) -> faire_projectMetadata_checklist_targeted

setdiff(faire_projectMetadata_checklist_targeted$term_name,colnames(sample_projectMetadata_pycno))


```

## Make Dataframe and export TSV

```{r}

sample_projectMetadata_pycno %>% 
  ungroup() %>% 
  slice(1) %>% 
    mutate(across(everything(), as.character)) %>% 
  pivot_longer(everything(), names_to = "term_name", values_to = "project_level") -> projectMetadata_pycno_long

faire_projectMetadata_checklist_targeted %>% 
  filter(., term_name !="biological_rep") %>% # biological rep differs per sample, not a project level entry
  add_row(requirement_level_code="O",	`section`="Targeted assay detection",	term_name = "estimatedNumberOfCopies_method", project_level = NA) %>%  # add in an older FAIRe term that we used
dplyr::select(-project_level) %>% 
  left_join(projectMetadata_pycno_long) -> projectMetadata_pycno

write.table(projectMetadata_pycno, file=here("FAIRe","PMEL","PMEL_projectMetadata_pycno.tsv"),sep = "\t", row.names = FALSE, quote = FALSE)

```

# Sample Metadata

```{r}

pycno_sample_data_run1 <- readRDS("raw_data/qPCR_raw_data/pycno_sample_data_run1.rds")
pycno_sample_data_run3 <- readRDS("raw_data/qPCR_raw_data/pycno_sample_data_run3.rds")
pycno_sample_data_run5_all <-  readRDS("raw_data/qPCR_raw_data/pycno_sample_data_run5_all.rds")
pycno_sample_data_run1$`Sample Name` %>% unique()
pycno_sample_data_run3$`Sample Name` %>% unique()
pycno_sample_data_run5_all$`Sample Name` %>% unique()

bind_rows(pycno_sample_data_run5_all, pycno_sample_data_run3, pycno_sample_data_run1) -> PMEL_all_runs
PMEL_all_runs$`Sample Name` %>%  unique() %>%  sort()
PMEL_all_runs$Species %>%  unique()



PMEL_all_runs %>% 
  mutate(., `Sample Name` = case_when(Task=="STANDARD" ~ paste0(`Target Name`,"_",Task,"_",round(Quantity,3)),
                                      Task=="NTC" ~ paste0(`Target Name`,"_",Task),
    TRUE ~ `Sample Name`)) %>% 
  group_by(`Sample Name`, Plate, Task) %>% 
  mutate(., group_idx=row_number()) %>% 
  ungroup() %>% 
 mutate(., Bottle_Name = case_when( Task=="UNKNOWN" & Sample_Type=="Sample" &str_starts(`Sample Name`, "E") ~ str_extract(`Sample Name`, "^[^.]+"),
                                    TRUE ~ NA)) %>% 
  group_by(Bottle_Name) %>% 
  mutate(., biological_rep= max(Biological_Replicate)) %>% 
   mutate(samp_name = paste0(`Sample Name`,"-",group_idx,"-Plate:",Plate)) %>% 
    ungroup() %>% 
   mutate(., samp_category= case_when(Task=="STANDARD" ~ "PCR standard",
                                      Species =="Pycnopodia helianthoides"~"positive control",
                                      Negative_control == TRUE ~ "negative control",
                                      str_detect(Name_plotting,"Aquarium")~"positive control",
          TRUE ~ "sample")) %>% 
  mutate(., neg_cont_type = case_when(samp_category=="negative control" & Class=="field blank" ~ "field negative",
                                      samp_category=="negative control" & Class=="extraction blank" ~ "extraction negative",
                                      samp_category=="negative control" & Class=="Tissue" & Species !="Pycnopodia helianthoides" ~"process negative",
                                      samp_category=="negative control" & Task=="NTC" ~"PCR negative",
                                      TRUE ~"")) %>% 
  mutate(., pos_cont_type = case_when(samp_category=="positive control" & str_detect(Name_plotting,"Aquarium") ~ "site positive",
                                      samp_category=="positive control" & Class=="Tissue" & Species =="Pycnopodia helianthoides" ~"extraction positive",
                                      Task=="STANDARD" ~"synthetic DNA",
                                      TRUE ~"")) %>% 
  mutate(., materialSampleID=str_c("UWFHL-Pycno-2025","_",`Sample Name`)) -> PMEL_all_runs_sampleMetadata
  
 PMEL_all_runs_sampleMetadata %>% 
  group_by(Plate) %>% 
  summarise(rel_cont_id = paste(samp_name, collapse = "|"), .groups = "drop") -> associated_samples
 
 PMEL_all_runs_sampleMetadata %>% 
   filter(., Station %in% c("Aquarium Discharge","FHL Dock","FHL Intake Pipes")) %>% 
  group_by(Station) %>% 
  summarise(biological_rep_relation = paste(samp_name, collapse = "|"), .groups = "drop") -> associated_bio_reps
 

PMEL_all_runs_sampleMetadata %>% 
  dplyr::select(samp_name,Collection_Date_local, Collection_Time_local) %>% 
  filter(., !is.na(Collection_Date_local)) %>% 
  mutate(Collection_DateTime_local = as.POSIXct(Collection_Date_local) + 
  hms::as_hms(Collection_Time_local),
 Collection_Time_local= hms::as_hms(Collection_Time_local)) %>% 
    mutate(eventDate = format(Collection_DateTime_local, "%Y-%m-%dT%H:%M:%S")) %>% 
  dplyr::select(samp_name,eventDate,verbatimEventDate=Collection_Date_local,				
verbatimEventTime=Collection_Time_local)-> event_date_info


PMEL_all_runs_sampleMetadata %>% 
  mutate(., env_medium = case_when(Station=="Aquarium Discharge"~"saline water aquarium [ENVO:00002197]",
                                   Station=="FHL Dock"~"sea water [ENVO:00002149]",
                                   Station=="FHL Intake Pipes"~"sea water [ENVO:00002149]",
                                   Class=="Tissue"~"tube foot [BTO:0001919]",
                                   samp_category=="negative control" ~ "sterile water [ENVO:00005791]",
                                   samp_category=="PCR standard" ~ "synthetic DNA [EFO:0004604]",
         TRUE ~ "weird" ),
         habitat_natural_artificial_0_1 = case_when(Station=="Aquarium Discharge" ~ 1,
                                                   Station=="FHL Dock" ~ 0,
                                   Station=="FHL Intake Pipes" ~ 0,
                                   Class=="Tissue" ~ 0,
                                   samp_category=="negative control" ~ 1,
                                   samp_category=="PCR standard" ~ 1,
                                   TRUE ~ 999)) %>% 
       dplyr::select(samp_name,env_medium,habitat_natural_artificial_0_1) -> env_medium_info


          
PMEL_all_runs_sampleMetadata %>% 
    mutate(., sample_derived_from = materialSampleID,
           sample_composed_of =materialSampleID) %>% 
    left_join(associated_samples) %>% 
    left_join(associated_bio_reps) %>% 
    rename(decimalLongitude=Lon,decimalLatitude=Lat) %>% 
    mutate(., geo_loc_name = "North East Pacific Ocean [GAZ:00013765]") %>% 
   left_join(event_date_info) %>% 
    mutate(., env_broad_scale = "marine biome [ENVO:00000447]",
          env_local_scale ="marine benthic biome [ENVO:01000024]") %>% 
    left_join(env_medium_info) %>% 
    mutate(., samp_collect_method = case_when(Field_collection_method=="Sterivex 0.22µm"~"https://doi.org/10.5281/zenodo.11398179",
                                              Field_collection_method=="Smith root 0.22 µm"~"https://doi.org/10.5281/zenodo.17655098",
                                       Field_collection_method=="Kringle Gauze"        ~"https://doi.org/10.64898/2026.05.07.723600",
                                        Field_collection_method=="Paint Roller"        ~"https://doi.org/10.64898/2026.05.07.723600",
                                       Field_collection_method=="Vivecare gauze"        ~"https://doi.org/10.64898/2026.05.07.723600",
                                        Field_collection_method=="Tische Environmental Filter"        ~"https://doi.org/10.64898/2026.05.07.723600",
                                       TRUE ~"https://doi.org/10.64898/2026.05.07.723600"),
           samp_collect_device=NA,
           samp_size = Sample_volume_ml,
           samp_size_unit = "mL",
           samp_store_temp	=-20,
           samp_store_sol="ethanol",
           samp_store_dur = case_when(Station %in% c("Aquarium Discharge","FHL Dock","FHL Intake Pipes") ~"P5D",
                                      TRUE ~"P218D"),
           samp_store_loc="NOAA PMEL OME Freezer B",
           dna_store_loc="NOAA PMEL OME Freezer B|NOAA PMEL OME Freezer D",
           samp_store_method_additional=NA) %>% 
         mutate(.,  samp_mat_process= case_when(Field_collection_method=="Sterivex 0.22µm"~"Seawater samples were filtered through a 0.22 µm PES Sterivex sterile filter capsule to capture eDNA and DNA-containing particulates using a peristaltic pump.",
                                              Field_collection_method=="Smith root 0.22 µm"~"Seawater samples were filtered through a 0.22 µm PES Smith Root sterile filter capsule to capture eDNA and DNA-containing particulates using a peristaltic pump.",
                                       Field_collection_method=="Kringle Gauze"        ~"Sterile Kringle Gauze were placed in a sterile plastic tub in seawater effluent for 1 hours.",
                                        Field_collection_method=="Paint Roller"        ~"Non-sterile Paint Rollers  were placed in a sterile plastic tub in seawater effluent for 1 hours.",
                                       Field_collection_method=="Vivecare gauze"        ~"Sterile Vivecare Gauze were placed in a sterile plastic tub in seawater effluent for 1 hours.",
                                        Field_collection_method=="Tische Environmental Filter"        ~"Non-sterile Tische Environmental Filter were placed in a sterile plastic tub in seawater effluent for 1 hours.",
                                       TRUE ~"")) %>% 
           mutate(., filter_passive_active_0_1= case_when(Field_collection_method=="Sterivex 0.22µm"~1,
                                              Field_collection_method=="Smith root 0.22 µm"~1,
                                       Field_collection_method=="Kringle Gauze"        ~0,
                                        Field_collection_method=="Paint Roller"        ~0,
                                       Field_collection_method=="Vivecare gauze"        ~0,
                                        Field_collection_method=="Tische Environmental Filter"~0,
                                       TRUE ~NA)) %>% 
           mutate(., stationed_sample_dur = if_else(filter_passive_active_0_1 == 0,"P1D",NA),
           pump_flow_rate = if_else(filter_passive_active_0_1 ==1,0.2,NA),
           pump_flow_rate_unit="L/min",
           prefilter_material=NA,
           size_frac_low = NA,
           size_frac=  if_else(filter_passive_active_0_1 ==1,0.2,NA),
           filter_diameter= if_else(Field_collection_method=="Smith root 0.22 µm",47,NA),
           filter_surface_area = case_when(Field_collection_method=="Sterivex 0.22µm"~1000,
                                              Field_collection_method=="Smith root 0.22 µm"~1730,
                                       Field_collection_method=="Kringle Gauze"        ~NA,
                                        Field_collection_method=="Paint Roller"        ~NA,
                                       Field_collection_method=="Vivecare gauze"        ~NA,
                                        Field_collection_method=="Tische Environmental Filter"~NA,
                                       TRUE ~NA),
           filter_material = case_when(Field_collection_method=="Sterivex 0.22µm"~"polyethersulfone",
                                              Field_collection_method=="Smith root 0.22 µm"~"polyethersulfone",
                                       Field_collection_method=="Kringle Gauze"        ~"cotton",
                                        Field_collection_method=="Paint Roller"        ~"polyester",
                                       Field_collection_method=="Vivecare gauze"        ~"cotton",
                                        Field_collection_method=="Tische Environmental Filter"~"polyurethane",
                                       TRUE ~""),
           filter_name = case_when(Field_collection_method=="Sterivex 0.22µm"~"Sterivex SVGPL10RC",
                                              Field_collection_method=="Smith root 0.22 µm"~"Smith Root eDNA Filter",
                                       Field_collection_method=="Kringle Gauze"        ~"Kringle Gauze",
                                        Field_collection_method=="Paint Roller"        ~"Paint Roller",
                                       Field_collection_method=="Vivecare gauze"        ~"Vivecare gauze",
                                        Field_collection_method=="Tische Environmental Filter"~"Tische Environmental Filter",
                                       TRUE ~""),
           precip_chem_prep=NA,
           precip_force_prep=NA,
           precip_time_prep=NA,
           precip_temp_prep=NA,
           prepped_samp_store_temp=-20,
           prepped_samp_store_sol = case_when(Field_collection_method=="Sterivex 0.22µm"~"ethanol",
                                              Field_collection_method=="Smith root 0.22 µm"~"ethanol",
                                       Field_collection_method=="Kringle Gauze"        ~NA,
                                        Field_collection_method=="Paint Roller"        ~NA,
                                       Field_collection_method=="Vivecare gauze"        ~NA,
                                        Field_collection_method=="Tische Environmental Filter"~NA,
                                       TRUE ~""),
           prepped_samp_store_dur = NA,
           prep_method_additional = NA,
           date_ext =  format(date_ext, "%Y-%m-%dT%H:%M:%S"),
           samp_vol_we_dna_ext = Sample_volume_ml,
           samp_vol_we_dna_ext_unit = "mL",
           nucl_acid_ext_lysis = "thermal | chemical",
           nucl_acid_ext_sep = "column-based",
           nucl_acid_ext = case_when(Field_collection_method=="Sterivex 0.22µm"~"https://doi.org/10.5281/zenodo.17655148",
                                              Field_collection_method=="Smith root 0.22 µm"~"https://doi.org/10.5281/zenodo.17655213",
                                       Field_collection_method=="Kringle Gauze"        ~"https://doi.org/10.5281/zenodo.17655213",
                                        Field_collection_method=="Paint Roller"        ~"https://doi.org/10.5281/zenodo.17655213",
                                       Field_collection_method=="Vivecare gauze"        ~"https://doi.org/10.5281/zenodo.17655213",
                                        Field_collection_method=="Tische Environmental Filter"        ~"https://doi.org/10.5281/zenodo.17655213",
                                       TRUE ~"https://doi.org/10.5281/zenodo.17655213"),
           nucl_acid_ext_kit = "Qiagen Blood and Tissue Kit",
           nucl_acid_ext_modify ="Modification following Spens et al. 2017. 720 µL ATL Buffer and 80 µL Proteinase K are added to the Sterivex filters. Add Buffer AL and ice-cold 100% EtOH in equal volume to recovered volume after incubation. All other methods follow the manufacturers' instructions.",
           dna_cleanup_0_1=0,
           dna_cleanup_method=NA,
           concentration = concentration,
           concentration_unit = "ng/µL",
           concentration_method = "Qubit 4.0 Fluorometer (Invitrogen)",
           assay_name = PMEL_qPCR_bebop_list$value[which(PMEL_qPCR_bebop_list$term=="assay_name")],
           detected_notDetected = if_else(CT =="Undetermined", "Not Detected", "Detected"),
           samp_weather="overcast",
           minimumDepthInMeters,				
           maximumDepthInMeters,
           tot_depth_water_col	
           ) -> pycno_sampleMetadata
 
				
				
pycno_sampleMetadata
		

```

## Check for Completeness
```{r}
bebop_total %>% 
  filter(., category=="FAIRe terms") -> bebop_faire_total_terms

setdiff(bebop_total$term,colnames(pycno_sampleMetadata))


setdiff(FAIRe_sampleMetadata_checklist$term,colnames(pycno_sampleMetadata))


```
## Make Dataframe and export TSV

```{r}

pycno_sampleMetadata %>% 
  dplyr::select(any_of(FAIRe_sampleMetadata_checklist$term)) -> sampleMetadata_pycno

write.table(sampleMetadata_pycno, file=here("FAIRe","PMEL","PMEL_sampleMetadata_pycno.tsv"),sep = "\t", row.names = FALSE, quote = FALSE)

```

# AmpData

```{r}


pycno_sampleMetadata %>% 
mutate(., estimatedNumberOfCopies=Quantity*2,
       CT=as.numeric(CT)) %>% # Added 2 µL of template DNA and standard, instrument was given information that concentration was 100 copies per µL. We added 200 copies per reaction, thus we need to multiply ny 2 to get copies per reaction
rename(., technical_rep_id= Technical_Replicate,
       pcr_plate_id=Plate,
       quantificationCycle=CT,
       ) %>% 
mutate(., estimatedNumberOfCopies_method= "Ct/Cq with standard curve",
       estimatedNumberOfCopies_unit="copies/reaction" ) -> pycno_ampData 

```


## Check for Completeness
```{r}
bebop_total %>% 
  filter(., category=="FAIRe terms") -> bebop_faire_total_terms

setdiff(bebop_total$term,colnames(pycno_sampleMetadata))

setdiff(FAIRe_ampData_checklist$term,colnames(pycno_ampData))

```
## Make Dataframe and export TSV

```{r}

pycno_ampData %>% 
  filter(., Task=="UNKNOWN") %>% 
  dplyr::select(any_of(FAIRe_ampData_checklist$term)) -> ampData_pycno

write.table(ampData_pycno, file=here("FAIRe","PMEL","PMEL_ampData_pycno.tsv"),sep = "\t", row.names = FALSE, quote = FALSE)

```

# stdData

```{r}

pycno_ampData %>% 
filter(., Task=="STANDARD") %>% 
mutate(., std_conc = estimatedNumberOfCopies,
       std_conc_unit = "copies/reaction",
       	efficiency=Efficiency, 	r2=`R(superscript 2)`,
       slope=Slope,
       intercept=`Y-Intercept`)  %>% 
  dplyr::select(any_of(FAIRe_stdData_checklist$term)) -> stdData_pycno


write.table(stdData_pycno, file=here("FAIRe","PMEL","PMEL_stdData_pycno.tsv"),sep = "\t", row.names = FALSE, quote = FALSE)
```

# eLowQuant LoD Filtered
```{r}

loblodloq_df <- read.delim(, file=here("LOD_LOQ","final_lob_lod_loq_table.csv"), sep=",") %>% 
  filter(., Type=="qPCR") %>% pivot_wider(names_from = LoD_method, values_from = c(LOB,LOD,LOQ)) %>% 
  mutate(., LOB_eLowQuant = if_else(is.na(LOB_eLowQuant),0, LOB_eLowQuant),
         LOD_eLowQuant = if_else(is.na(LOD_eLowQuant),0.2134723, LOD_eLowQuant),
         LOQ_eLowQuant = if_else(is.na(LOQ_eLowQuant),0.8078273, LOQ_eLowQuant)) %>% 
  mutate(., Plate = as.numeric(str_sub(Plate,-1)))

ampData_pycno %>% 
  left_join(loblodloq_df, by=c("pcr_plate_id"="Plate")) %>% 
  mutate(., LoDLoQLevel = case_when(estimatedNumberOfCopies > LOQ_Klymus ~ "Above LOQ_Klymus & LOQ_eLowQuant",
         estimatedNumberOfCopies > LOD_Klymus ~ "Above LOD_Klymus & LOQ_eLowQuant",
         estimatedNumberOfCopies > LOQ_eLowQuant ~ "Above LOQ_eLowQuant",
              estimatedNumberOfCopies > LOD_eLowQuant ~ "Above LOD_eLowQuant",                      
         estimatedNumberOfCopies > LOB_eLowQuant ~ "Above LOB_eLowQuant",
                TRUE ~ "No Amplification" )) %>% 
  mutate(., estimatedNumberOfCopies = case_when(estimatedNumberOfCopies > LOD_eLowQuant ~ estimatedNumberOfCopies,
                         estimatedNumberOfCopies < LOD_eLowQuant ~ 0)) -> pycno_eLowQuantData
  

pycno_eLowQuantData %>% 
  dplyr::select(any_of(c(FAIRe_ampData_checklist$term,"LoDLoQLevel"))) -> eLowQuantData_pycno

write.table(eLowQuantData_pycno, file=here("FAIRe","PMEL","PMEL_eLowQuantData_pycno.tsv"),sep = "\t", row.names = FALSE, quote = FALSE)

```


