---
title: "Primer-Probe Mismatch Figure"
author: "Sean McAllister"
date: "2026-02-27"
output: html_document
---
# Load in Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggseqlogo)
```

# User Variables
```{r}
#Export/Import info
exportdir <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/"

input_Fprimer_pycno_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/forwardPrimer_Pycnopodia.tsv"
input_Fprimer_asteroids_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/forwardPrimer_Asteroidea.tsv"
input_Rprimer_pycno_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/reversePrimer_Pycnopodia.tsv"
input_Rprimer_asteroids_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/reversePrimer_Asteroidea.tsv"
input_probe_pycno_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/probe_Pycnopodia.tsv"
input_probe_asteroids_path <- "/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/probe_Asteroidea.tsv"

```

# Set the working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = exportdir)

```

# Import sequence data
```{r}
input_Fprimer_pycno <- readLines(input_Fprimer_pycno_path)
input_Fprimer_asteroids <- readLines(input_Fprimer_asteroids_path)
input_Rprimer_pycno <- readLines(input_Rprimer_pycno_path)
input_Rprimer_asteroids <- readLines(input_Rprimer_asteroids_path)
input_probe_pycno <- readLines(input_probe_pycno_path)
input_probe_asteroids <- readLines(input_probe_asteroids_path)

seqs_list <- list(
  F_primer_Pycnopodia = input_Fprimer_pycno,
  F_primer_Asteroidea = input_Fprimer_asteroids,
  R_primer_Pycnopodia = input_Rprimer_pycno,
  R_primer_Asteroidea = input_Rprimer_asteroids,
  probe_Pycnopodia = input_probe_pycno,
  probe_Asteroidea = input_probe_asteroids
)
```

# Create sequence logos
```{r}
logo_plot <- ggseqlogo(seqs_list, facet = "wrap", method = 'bits', ncol = 1)

```

# Heatmap
```{r}
library(pheatmap)

input_heatmap <- read_delim("/Users/mcallister/Desktop/03_Projects/Zack/Pycnopodia_assay/primer_probe_alignments_ALLin/heatmap_best.txt")
input_heatmap <- column_to_rownames(input_heatmap, var = "Specimen")

pheat <- pheatmap(
  as.matrix(input_heatmap),
  cluster_cols = FALSE,
  #cluster_rows = FALSE,
  display_numbers = TRUE,
  number_format = "%.0f",
  color = colorRampPalette(c("white","yellow","orange","red"))(50)
)
```

# Figure facet
```{r}
library(cowplot)

heatmap_plot <- pheat$gtable

combined_plot <- plot_grid(
  logo_plot,
  heatmap_plot,
  ncol = 2,
  rel_widths = c(1,1)
)

combined_plot


```